/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef ClassifyService_CONSTANTS_H
#define ClassifyService_CONSTANTS_H

#include "ClassifyService_types.h"



class ClassifyServiceConstants {
 public:
  ClassifyServiceConstants();

};

extern const ClassifyServiceConstants g_ClassifyService_constants;



#endif
